[tool.poetry]
name = "interact"
version = "0.1.0"
description = "Interact with LLMs"
authors = ["Pritam Dey <pritam.pritamdey.984@gmail.com>"]
readme = "README.md"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[dependencies]
python = "^3.10"
openai = "^0.27"
# Add your dependencies here

[tool.poetry.dev-dependencies]
# Add development dependencies here
