name: Deploy docs
on: [push]
permissions:
  contents: write
jobs:
  deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Set up Python 🐍
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # Specify Python 3.12

      - name: Install pipx and Poetry 🔧
        run: |
            python3 -m pip install --user pipx
            python3 -m pipx ensurepath
            pipx install poetry
            poetry install --no-root --only dev

      - name: Build docs 📚
        run: |
          cd docs
          poetry run make html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/_build/html
          branch: docs
